### ISSUE TITLE
please update to Gophercon videos

### ISSUE THREAD

**Issue by soniah** [JetBrains/golandtipsandtricks#1]
Hi Florin, would you please update the repo to the examples you were using during the Gophercon videos? Thanks.

**Comment by dlsniper** [comment]
Hi @soniah,

The examples during the GopherCon videos are now all in the repository.
We always welcome contributions, so if you stumble upon a feature you like, don't hesitate to raise an issue to add it to the repository, or send a PR with it.
Thank you!
