### ISSUE TITLE
Please add "goland.desktop" to support gnome desktop shortcut

### ISSUE THREAD

**Issue by orestonce** [JetBrains/golandtipsandtricks#2]
````
$ cat /usr/share/applications/goland.desktop
[Desktop Entry]
Name=Goland
Exec=/opt/goland/bin/goland.sh
Terminal=false
Type=Application
````

**Comment by dlsniper** [comment]
Hi @orestonce. I'm not sure I understand what I should do with this.
From what I can tell, this is how a Gnome icon looks like.
But what should I do with it?
Thank you.

**Comment by orestonce** [comment]
just put it in goland.tar.gz

**Comment by dlsniper** [comment]
I'm afraid we cannot simply do that.
One of the reasons would be that not everyone installs the IDE under `/opt/goland`. For example, I have it under `/home/florin/GoLand20X.Y`. 

If you are looking for a way to create a shortcut to the IDE, please look at our [Documentation](https://www.jetbrains.com/help/go/working-with-the-ide-features-from-command-line.html).
