### ISSUE TITLE
Please modify the goland default formatting to the goimports

### ISSUE THREAD

**Issue by ghost** [JetBrains/golandtipsandtricks#5]
Now, `goimports` automatically imports expansion packages and distinguishes between built -in and extermal expansion packages, create two blocks of packages. It's easy to distinguish

First, Less people set file watchers in the goland, so `gofmt` is used in te project to sort the list of extended packages. 
Other editors, such as vscode, use `goimports` by default. This will cause unnecessary trouble.

`goimports` is better than `gofmt`, more intuitive, please set the goimports to formatting instead of having to

**Comment by dlsniper** [comment]
Hi. This tracker is not meant to raise such types of concerns. Please use: https://youtrack.jetbrains.com/issues/Go Thank you.
